# Generated by Django 2.2.10 on 2021-11-03 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IDUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OprosModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название опроса')),
                ('start_date', models.DateField(null=True, verbose_name='Дата начала опроса')),
                ('end_date', models.DateField(null=True, verbose_name='Конечная дата опроса')),
                ('description', models.TextField(verbose_name='Описание опроса')),
            ],
            options={
                'verbose_name_plural': 'Опрос',
            },
        ),
        migrations.CreateModel(
            name='ResultOpros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_matter', models.TextField(max_length=100, verbose_name='Вопрос')),
                ('number_matter', models.IntegerField()),
                ('text_answer', models.TextField(blank=True, max_length=100, null=True, verbose_name='тесктовый вариант ответа')),
                ('option_answer1', models.CharField(blank=True, max_length=100, null=True, verbose_name='вариант ответа 1')),
                ('option_answer2', models.CharField(blank=True, max_length=100, null=True, verbose_name='вариант ответа 2')),
                ('option_answer3', models.CharField(blank=True, max_length=100, null=True, verbose_name='вариант ответа 3')),
                ('option_answer4', models.CharField(blank=True, max_length=100, null=True, verbose_name='вариант ответа 4')),
                ('opros', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opros.OprosModel', verbose_name='Опрос')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opros.IDUser', verbose_name='Результат опороса')),
            ],
            options={
                'verbose_name_plural': 'Ответ на вопрос',
            },
        ),
        migrations.CreateModel(
            name='MatterModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_matter', models.TextField(max_length=100, verbose_name='Вопрос')),
                ('number_matter', models.IntegerField()),
                ('text_answer', models.TextField(blank=True, max_length=100, null=True, verbose_name='тесктовый вариант ответа')),
                ('option_answer1', models.CharField(blank=True, max_length=100, null=True, verbose_name='вариант ответа 1')),
                ('option_answer2', models.CharField(blank=True, max_length=100, null=True, verbose_name='вариант ответа 2')),
                ('option_answer3', models.CharField(blank=True, max_length=100, null=True, verbose_name='вариант ответа 3')),
                ('option_answer4', models.CharField(blank=True, max_length=100, null=True, verbose_name='вариант ответа 4')),
                ('type_matter', models.CharField(choices=[('ОД', 'Один ответ на выбор'), ('МН', 'Множественный ответ'), ('ТК', 'Текстовый ответ')], default='ОД', max_length=2, verbose_name='Тип ответа')),
                ('opros', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opros.OprosModel', verbose_name='Опрос')),
            ],
            options={
                'verbose_name_plural': 'Вопрос',
            },
        ),
    ]
